### ISSUE TITLE
回调地址怎么填

### ISSUE THREAD

**Issue by zdxiaoda** [jiyeme/Go-Login#1]
如题

**Comment by msojocs** [comment]
[https://github.com/jiyeme/Go-Login#%E5%9B%9E%E8%B0%83%E5%9C%B0%E5%9D%80](https://github.com/jiyeme/Go-Login#%E5%9B%9E%E8%B0%83%E5%9C%B0%E5%9D%80)

**Comment by zdxiaoda** [comment]
> [https://github.com/jiyeme/Go-Login#%E5%9B%9E%E8%B0%83%E5%9C%B0%E5%9D%80](https://github.com/jiyeme/Go-Login#%E5%9B%9E%E8%B0%83%E5%9C%B0%E5%9D%80)

这里没看懂。。。
我自己的站没有用
blog.zhangda.xyz

**Comment by msojocs** [comment]
domain换成域名
domain/Gologin/callback/qq  ---->  http://blog.zhangda.xyz/Gologin/callback/qq

禁用一下其它插件，

**Comment by zdxiaoda** [comment]
> domain换成域名
> domain/Gologin/callback/qq  ---->  http://blog.zhangda.xyz/Gologin/callback/qq
> 
> 禁用一下其它插件，

好，谢谢，我看看插件- ̗̀(๑ᵔ⌔ᵔ๑)

**Comment by zdxiaoda** [comment]
> > domain换成域名
> > domain/Gologin/callback/qq  ---->  http://blog.zhangda.xyz/Gologin/callback/qq
> > 
> > 禁用一下其它插件，
> 
> 好，谢谢，我看看插件- ̗̀(๑ᵔ⌔ᵔ๑)

啊这，我禁用了所有其他插件，换了主题，还是不行

**Comment by msojocs** [comment]
把缓存关了

**Comment by zdxiaoda** [comment]
> 把缓存关了

ok

**Comment by zdxiaoda** [comment]
> 把缓存关了

啊这，还是不行，不会不支持WordPress 5.6吧。。。

**Comment by msojocs** [comment]
抱歉，我这也是5.6，
暂时不清楚什么原因导致的。

**Comment by zdxiaoda** [comment]
> 抱歉，我这也是5.6，
> 暂时不清楚什么原因导致的。

真实太奇怪了。。。😂

**Comment by msojocs** [comment]
> > 抱歉，我这也是5.6，
> > 暂时不清楚什么原因导致的。
> 
> 真实太奇怪了。。。😂

不嫌麻烦的话，开启WP调试，看看有没有什么奇怪的报错。
